import Link from "next/link";
import { db } from "@/lib/db";
import { RatingStars } from "@/components/rating-stars";
import { AppSearch } from "@/components/app-search";
import { ChevronRight, SlidersHorizontal } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function AppsPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; sort?: string }> }) {
  const params = await searchParams; const q = params.q?.trim() ?? ""; const category = params.category?.trim(); const sort = params.sort === "rating" ? "rating" : "updated";
  const apps = await db.app.findMany({ where: { enabled: true, ...(category ? { category } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { developerName: { contains: q, mode: "insensitive" } }, { bundleId: { contains: q, mode: "insensitive" } }, { description: { contains: q, mode: "insensitive" } }] } : {}) }, include: { releases: { where: { draft: false }, include: { assets: true }, orderBy: { publishedAt: "desc" }, take: 1 } }, orderBy: { updatedAt: "desc" } });
  const ratingGroups = apps.length ? await db.appRating.groupBy({ by: ["appId"], where: { appId: { in: apps.map((app) => app.id) } }, _avg: { rating: true }, _count: { rating: true } }) : [];
  const ratings = new Map(ratingGroups.map((r) => [r.appId, { average: r._avg.rating ?? 0, count: r._count.rating ?? 0 }]));
  if (sort === "rating") apps.sort((a, b) => ((ratings.get(b.id)?.count ?? 0) - (ratings.get(a.id)?.count ?? 0)) || ((ratings.get(b.id)?.average ?? 0) - (ratings.get(a.id)?.average ?? 0)));

  return <main className="mx-auto max-w-6xl px-4 sm:px-5 lg:px-8"><div className="flex items-center justify-between py-5"><Link href="/" className="text-sm font-medium text-gray-500 md:hidden">SideloadHub</Link><div className="hidden md:block" /><Link href="/submit" className="rounded-xl bg-black px-4 py-2 text-sm font-semibold text-white dark:bg-white dark:text-black">Add repository</Link></div>
    <section className="pb-5 pt-5 md:pt-12"><p className="text-xs font-semibold uppercase tracking-[.12em] text-blue-600">Catalog</p><div className="mt-2 flex items-end justify-between gap-3"><div><h1 className="text-[36px] font-bold tracking-[-.04em] md:text-6xl">Apps</h1><p className="mt-2 text-sm text-gray-500 md:text-base">Independent iOS apps ready for sideloading.</p></div><span className="hidden rounded-full bg-black/[.04] px-3 py-1.5 text-xs font-semibold text-gray-500 md:block dark:bg-white/[.06]">{apps.length} apps</span></div></section>
    <div className="sticky top-0 z-20 -mx-4 bg-[var(--background)]/90 px-4 pb-3 pt-1 backdrop-blur-xl sm:static sm:mx-0 sm:px-0"><AppSearch initialQuery={q} /><div className="mt-3 flex gap-2 overflow-x-auto pb-1"><Link href={q ? `/apps?q=${encodeURIComponent(q)}` : "/apps"} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${sort === "updated" ? "bg-black text-white dark:bg-white dark:text-black" : "border border-black/10 text-gray-600 dark:border-white/10 dark:text-gray-300"}`}>Recently updated</Link><Link href={q ? `/apps?q=${encodeURIComponent(q)}&sort=rating` : "/apps?sort=rating"} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${sort === "rating" ? "bg-black text-white dark:bg-white dark:text-black" : "border border-black/10 text-gray-600 dark:border-white/10 dark:text-gray-300"}`}><SlidersHorizontal className="mr-1 inline h-3 w-3" />Top rated</Link></div></div>
    <div className="grid gap-3 pb-12 sm:grid-cols-2 lg:grid-cols-3">{apps.map((app) => { const latest = app.releases[0]; const rating = ratings.get(app.id); return <Link key={app.id} href={`/apps/${app.slug}`} className="group rounded-[22px] border border-black/[.08] bg-white p-4 shadow-sm transition active:scale-[.99] hover:shadow-md dark:border-white/[.09] dark:bg-white/[.04]"><div className="flex items-center gap-3.5"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-[19px] bg-gray-100 text-xl dark:bg-white/10">{app.iconUrl ? <img src={app.iconUrl} alt="" className="h-full w-full object-cover" /> : "✦"}</div><div className="min-w-0 flex-1"><h2 className="truncate font-semibold">{app.name}</h2><p className="truncate text-xs text-gray-500">{app.developerName}</p>{latest && <p className="mt-1 text-xs font-medium text-gray-400">Latest · v{latest.version}</p>}</div><ChevronRight className="h-5 w-5 shrink-0 text-gray-300" /></div><p className="mt-3 line-clamp-2 text-sm leading-5 text-gray-500">{app.description || "Independent iOS app distributed from GitHub."}</p><div className="mt-3 flex items-center justify-between gap-2">{rating ? <RatingStars slug={app.slug} average={rating.average} count={rating.count} /> : <span className="rounded-full bg-gray-100 px-2.5 py-1 text-[11px] font-medium text-gray-500 dark:bg-white/10">{app.category}</span>} {rating && <span className="rounded-full bg-gray-100 px-2.5 py-1 text-[11px] font-medium text-gray-500 dark:bg-white/10">{app.category}</span>}</div></Link>; })}</div>
    {apps.length === 0 && <div className="rounded-[22px] border border-dashed border-black/10 p-12 text-center text-sm text-gray-500 dark:border-white/10">No apps found yet.</div>}
  </main>;
}
