import Link from "next/link";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { RatingStars } from "@/components/rating-stars";
import { SourceActions } from "@/components/source-actions";
import { ArrowLeft, Download, Github, Package } from "lucide-react";

export const dynamic = "force-dynamic";
function getRequestOrigin(h: Headers) { const configured = process.env.NEXT_PUBLIC_SITE_URL?.trim().replace(/\/$/, ""); if (configured && !/localhost|127\.0\.0\.1/i.test(configured)) return configured; const host = h.get("x-forwarded-host") || h.get("host"); return host ? `${h.get("x-forwarded-proto") || "https"}://${host}` : configured || "http://localhost:3000"; }

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const app = await db.app.findFirst({ where: { slug, enabled: true }, include: { repositories: { include: { repository: true }, take: 1 }, releases: { where: { draft: false }, include: { assets: true }, orderBy: { publishedAt: "desc" } } } }); if (!app) notFound();
  const aggregate = await db.appRating.aggregate({ where: { appId: app.id }, _avg: { rating: true }, _count: { rating: true } }); const average = aggregate._avg.rating ?? 0; const count = aggregate._count.rating ?? 0; const latest = app.releases[0]; const repoName = app.repositories[0]?.repository.repository; const sourceUrl = repoName ? `${getRequestOrigin(await headers())}/${encodeURIComponent(repoName)}/source.json` : null;
  return <main className="mx-auto max-w-5xl px-4 sm:px-5 lg:px-8"><div className="flex items-center justify-between py-4"><Link href="/apps" className="inline-flex min-h-10 items-center gap-1.5 text-sm font-medium text-gray-500"><ArrowLeft className="h-4 w-4" />Apps</Link><Link href={app.githubRepositoryUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-black/10 px-3 text-sm font-semibold dark:border-white/10"><Github className="h-4 w-4" />GitHub</Link></div>
    <section className="pb-7 pt-5"><div className="flex items-start gap-4"><div className="grid h-[88px] w-[88px] shrink-0 place-items-center overflow-hidden rounded-[25px] bg-gray-100 text-3xl shadow-sm dark:bg-white/10">{app.iconUrl ? <img src={app.iconUrl} alt="" className="h-full w-full object-cover" /> : "✦"}</div><div className="min-w-0 flex-1"><h1 className="text-[32px] font-bold leading-tight tracking-[-.035em]">{app.name}</h1><p className="mt-1 text-sm text-gray-500">{app.developerName}</p><div className="mt-3"><RatingStars slug={app.slug} average={average} count={count} /></div></div></div>{app.description && <p className="mt-5 text-[15px] leading-6 text-gray-600 dark:text-gray-300">{app.description}</p>}
      {latest?.assets.length ? <div className="mt-5 space-y-2">{latest.assets.map((asset) => <a key={asset.id} href={asset.downloadUrl} target="_blank" rel="noreferrer" title={`Download ${asset.fileName}`} className="flex min-h-14 w-full items-center gap-3 rounded-2xl bg-black px-4 text-sm font-semibold text-white shadow-sm transition active:scale-[.99] dark:bg-white dark:text-black"><Download className="h-5 w-5 shrink-0" /><span className="min-w-0 flex-1 truncate">Download {asset.fileName}</span><span className="text-xs font-medium opacity-60">IPA</span></a>)}</div> : null}
    </section>
    {sourceUrl && <SourceActions sourceUrl={sourceUrl} />}
    <section className="pb-12 pt-9"><div className="mb-4 flex items-center gap-2"><Package className="h-5 w-5" /><h2 className="text-xl font-bold tracking-tight">Version history</h2></div><div className="space-y-3">{app.releases.map((r) => <article key={r.id} className="rounded-[20px] border border-black/[.08] bg-white p-4 dark:border-white/[.09] dark:bg-white/[.04]"><div className="flex items-center justify-between gap-3"><div><strong className="text-sm">v{r.version}</strong>{r.publishedAt && <span className="ml-2 text-xs text-gray-400">{r.publishedAt.toLocaleDateString()}</span>}</div><span className="text-xs text-gray-400">{r.assets.length} IPA{r.assets.length === 1 ? "" : "s"}</span></div><div className="mt-3 space-y-2">{r.assets.map((asset) => <a key={asset.id} href={asset.downloadUrl} target="_blank" rel="noreferrer" className="flex min-h-11 items-center gap-2 rounded-xl border border-black/[.08] px-3 text-xs font-semibold dark:border-white/[.09]"><Download className="h-4 w-4 shrink-0" /><span className="min-w-0 truncate">Download {asset.fileName}</span></a>)}</div>{r.releaseNotes && <p className="mt-3 whitespace-pre-wrap text-sm leading-5 text-gray-500">{r.releaseNotes}</p>}</article>)}</div></section>
  </main>;
}
