import Link from "next/link";
import { db } from "@/lib/db";
import { RatingStars } from "@/components/rating-stars";
import { ArrowRight, Download, Star } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function Home() {
  const recentRepositories = await db.repository.findMany({ where: { enabled: true }, orderBy: { createdAt: "desc" }, take: 10, include: { apps: { include: { app: { include: { releases: { where: { draft: false }, orderBy: { publishedAt: "desc" }, take: 1, include: { assets: true } } } } }, orderBy: { createdAt: "asc" }, take: 1 } } });
  const appIds = recentRepositories.flatMap((repo) => repo.apps.map((link) => link.app.id));
  const recentRatings = appIds.length ? await db.appRating.groupBy({ by: ["appId"], where: { appId: { in: appIds } }, _avg: { rating: true }, _count: { rating: true } }) : [];
  const ratingMap = new Map(recentRatings.map((r) => [r.appId, { average: r._avg.rating ?? 0, count: r._count.rating ?? 0 }]));
  const topRatingGroups = await db.appRating.groupBy({ by: ["appId"], _avg: { rating: true }, _count: { rating: true }, orderBy: [{ _count: { rating: "desc" } }, { _avg: { rating: "desc" } }], take: 6 });
  const topApps = topRatingGroups.length ? await db.app.findMany({ where: { id: { in: topRatingGroups.map((r) => r.appId) }, enabled: true } }) : [];
  const topAppMap = new Map(topApps.map((app) => [app.id, app]));

  return <main className="mx-auto max-w-6xl px-4 sm:px-5 lg:px-8">
    <section className="pb-10 pt-6 md:pb-16 md:pt-14"><div className="flex items-center gap-2 text-xs font-semibold text-blue-600"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-50 dark:bg-blue-500/10">✦</span>Made for iOS sideloading</div><h1 className="mt-5 max-w-3xl text-[42px] font-bold leading-[1.02] tracking-[-.045em] sm:text-6xl lg:text-7xl">Your home for sideloaded apps.</h1><p className="mt-5 max-w-xl text-base leading-7 text-gray-500 sm:text-lg">Discover independent iOS apps, grab the latest IPA, or add a source to AltStore and SideStore.</p><div className="mt-7 flex gap-2"><Link href="/apps" className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-2xl bg-black px-5 text-sm font-semibold text-white shadow-sm dark:bg-white dark:text-black sm:flex-none">Browse apps<ArrowRight className="h-4 w-4" /></Link><Link href="/submit" className="inline-flex min-h-12 items-center justify-center rounded-2xl border border-black/10 bg-white px-5 text-sm font-semibold dark:border-white/10 dark:bg-white/[.04]">Add repository</Link></div></section>

    <section className="pb-10"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-gray-400">Fresh releases</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Recently added</h2></div><Link href="/apps" className="text-sm font-semibold text-blue-600">See all</Link></div>{recentRepositories.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{recentRepositories.map((repo) => { const app = repo.apps[0]?.app; const release = app?.releases[0]; const rating = app ? ratingMap.get(app.id) : undefined; return <Link key={repo.id} href={app ? `/apps/${app.slug}` : "/submit"} className="group rounded-[22px] border border-black/[.08] bg-white p-4 shadow-sm transition active:scale-[.99] hover:-translate-y-0.5 hover:shadow-md dark:border-white/[.09] dark:bg-white/[.04]"><div className="flex items-center gap-3.5"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-[17px] bg-gray-100 text-xl dark:bg-white/10">{app?.iconUrl ? <img src={app.iconUrl} alt="" className="h-full w-full object-cover" /> : "✦"}</div><div className="min-w-0 flex-1"><h3 className="truncate font-semibold">{app?.name ?? repo.repository}</h3><p className="truncate text-xs text-gray-500">{app?.developerName ?? `github.com/${repo.owner}`}</p>{release && <p className="mt-1 text-xs text-gray-400">v{release.version}</p>}</div><ArrowRight className="h-4 w-4 shrink-0 text-gray-300 transition group-hover:translate-x-0.5" /></div>{app && rating && <div className="mt-3"><RatingStars slug={app.slug} average={rating.average} count={rating.count} /></div>}</Link>; })}</div> : <div className="rounded-[22px] border border-dashed border-black/10 p-10 text-center text-sm text-gray-500 dark:border-white/10">No repositories yet.</div>}</section>

    <section className="pb-12"><div className="mb-4 flex items-end justify-between"><div><p className="flex items-center gap-1 text-xs font-semibold uppercase tracking-[.12em] text-amber-500"><Star className="h-3.5 w-3.5 fill-current" />Community</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Top rated</h2></div><Link href="/apps?sort=rating" className="text-sm font-semibold text-blue-600">See all</Link></div>{topRatingGroups.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{topRatingGroups.map((group) => { const app = topAppMap.get(group.appId); if (!app) return null; return <Link key={app.id} href={`/apps/${app.slug}`} className="flex items-center gap-3 rounded-[22px] border border-black/[.08] bg-white p-4 dark:border-white/[.09] dark:bg-white/[.04]"><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-2xl bg-gray-100 dark:bg-white/10">{app.iconUrl ? <img src={app.iconUrl} alt="" className="h-full w-full object-cover" /> : "✦"}</div><div className="min-w-0 flex-1"><h3 className="truncate font-semibold">{app.name}</h3><p className="truncate text-xs text-gray-500">{app.developerName}</p><div className="mt-1 flex items-center gap-1 text-xs text-amber-500"><Star className="h-3 w-3 fill-current" />{(group._avg.rating ?? 0).toFixed(1)} <span className="text-gray-400">({group._count.rating})</span></div></div></Link>; })}</div> : <div className="rounded-[22px] border border-dashed border-black/10 p-10 text-center text-sm text-gray-500 dark:border-white/10">Ratings will appear here.</div>}</section>
    <footer className="hidden border-t border-black/[.07] py-8 text-sm text-gray-400 md:flex md:justify-between dark:border-white/[.08]"><span>© {new Date().getFullYear()} SideloadHub</span><Link href="/submit">Add Repository</Link></footer>
  </main>;
}
